### ISSUE TITLE
Codex with Emacs

### ISSUE THREAD

**Issue by achudnov** [aloiscochard/codex#10]
Is anybody using codex with Emacs? I'm generating a tags file, but Emacs refuses to open it complaining about invalid format. Here's what I have in my .codex:

```
hackagePath: .cabal-sandbox/packages/hackage.haskell.org/
tagsCmd: hasktags -e -a --output='$TAGS' '$SOURCES'
```

**Comment by vyorkin** [comment]
I'm trying to use codex `0.6.0.0` with Emacs, but I'm getting:
```
Error loading tags-file: (user-error File /home/vyorkin/projects/learn/haskell/diehl/TAGS is not a valid tags table) [2 times]
```

Here is my config file for `codex`:
```
currentProjectIncluded: true
hackagePath: /home/vyorkin/.cabal/packages/hackage.haskell.org/
tagsFileHeader: false
tagsFileName: TAGS
tagsFileSorted: false
tagsCmd: hasktags --etags --follow-symlinks --output="$TAGS" "$SOURCES"
stackOpts: ''
```

So the header and sorting options are disabled... Is there anyting else I can try?

**Comment by parsonsmatt** [comment]
I also get this with vim, so I suspect something is wrong with how the tags files are being generated.

**Comment by dmjio** [comment]
I get this as well.

**Comment by carlosdagos** [comment]
I noticed this happens if I first generate tags using `ctags` and then try to generate them again but using `etags`.

What I did was find all the tags files (in my case for `stack`):

```
find $HOME/.stack/indices/Hackage/packages -name 'tags'
```

I removed them and rebuilt my tags using `codex` again, and all worked 👍🏼
