### ISSUE TITLE
# [Codecov](https://codecov.io/gh/prysmaticlabs/prysm/pull/1363?src=pr&el=h1) Report

### ISSUE THREAD

**Issue by elizgarcia5** [aloiscochard/codex#105]
# [Codecov](https://codecov.io/gh/prysmaticlabs/prysm/pull/1363?src=pr&el=h1) Report
> Merging [#1363](https://codecov.io/gh/prysmaticlabs/prysm/pull/1363?src=pr&el=desc) into [master](https://codecov.io/gh/prysmaticlabs/prysm/commit/5cb361895d58aa03342990b541dc0bbf34c11c9c?src=pr&el=desc) will **increase** coverage by `2.25%`.
> The diff coverage is `n/a`.

```diff
@@            Coverage Diff             @@
##           master    #1363      +/-   ##
==========================================
+ Coverage   71.61%   73.87%   +2.25%     
==========================================
  Files          64       88      +24     
  Lines        4728     6576    +1848     
==========================================
+ Hits         3386     4858    +1472     
- Misses       1052     1313     +261     
- Partials      290      405     +115
```

__Originally posted by @codecov in https://github.com/prysmaticlabs/prysm/pull/1363#issuecomment-456281300__

**Comment by aloiscochard** [comment]
@elizgarcia5 this seems unraleted to this repository, or am I missing something?
