### ISSUE TITLE
Replace `download-curl`.

### ISSUE THREAD

**Issue by aloiscochard** [aloiscochard/codex#28]
With something "stackage friendly", see https://github.com/fpco/stackage/pull/404.

**Comment by rgrinberg** [comment]
+999 on this. You can even use the normal curl package with this little module from download-curl https://github.com/GaloisInc/curl/pull/11 to port codex very very fast.

Although curl isn't particularly well maintained either so perhaps there are better alternatives.

**Comment by aloiscochard** [comment]
Fixed with https://github.com/aloiscochard/codex/commit/6ae9ed7512b6ec47e273fb10a6d3d3762f3e9283

Thanks @rgrinberg you rocks!
