### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by nh2** [aloiscochard/codex#33]
Hi,

my generated tags files have many duplicate lines. Shouldn't `mergeTags` remove duplicates somehow? It doesn't seem to.

Thanks!

**Comment by aloiscochard** [comment]
Oops I have missed that one, sorry!

The fix seems reasonable, I'll try to do some testing asap. 

Thanks a lot!

**Comment by aloiscochard** [comment]
Fixed with: https://github.com/aloiscochard/codex/commit/7ca9badce88152e1b91f9bd65cdd022d9531d534

**Comment by nh2** [comment]
Thank you!

And +1 for not using dreaded `nub`!

**Comment by aloiscochard** [comment]
@nh2 I must shamefully confess that I tried first to use it, and then cried when looking at the performance.

Hopefully, I then ended on this great resource of yours:
https://github.com/nh2/haskell-ordnub

:-)
