### ISSUE TITLE
Unable to install codex with cabal

### ISSUE THREAD

**Issue by MarcoSero** [aloiscochard/codex#40]
I've been trying to install `codex` without success.

There seems to be a problem installing one of its dependencies, `mono-traversable`.

This is the log:
```
Resolving dependencies...
Configuring mono-traversable-0.9.2.1...
Building mono-traversable-0.9.2.1...
Failed to install mono-traversable-0.9.2.1
Build log ( /Users/marco/.cabal/logs/mono-traversable-0.9.2.1.log ):
Configuring mono-traversable-0.9.2.1...
Building mono-traversable-0.9.2.1...
Preprocessing library mono-traversable-0.9.2.1...
[1 of 7] Compiling Data.ByteVector  ( src/Data/ByteVector.hs, dist/build/Data/ByteVector.o )
[2 of 7] Compiling Data.MonoTraversable ( src/Data/MonoTraversable.hs, dist/build/Data/MonoTraversable.o )

src/Data/MonoTraversable.hs:93:48:
    Module ‘Data.Semigroup’ does not export ‘Arg’
cabal: Error: some packages failed to install
```

I'm using cabal version 1.20.0.2
Unfortunately I can't upgrade because of a [different problem](https://github.com/kazu-yamamoto/ghc-mod/wiki/InconsistentCabalVersions) that new versions have with `ghc-mod`.

Has anyone else seen this before?

**Comment by kevinclancy** [comment]
I had the same problem. What GHC version are you using? I'm using 7.10.2; maybe codex is not compatible with it. 

I worked around the problem by cloning the mono-traversable repo and installing it in the same sandbox as codex.

**Comment by MarcoSero** [comment]
Yeah it could be it's because I'm running 7.8.3

I fixed it by passing `--constraint=mono-traversable==0.9.0.*` to cabal. Not sure if it was a good idea but it worked :)
