### ISSUE TITLE
Keep going if a package is not in Hackage

### ISSUE THREAD

**Issue by chreekat** [aloiscochard/codex#43]
One of stack's features is specifying dependencies as git repos: [Snowdrift example](https://git.gnu.io/snowdrift/snowdrift/blob/master/stack.yaml#L6).

While I should probably clean up ghci-runner and add it it Hackage, it would be nice if codex just skipped it for now and continued running on everything else.

**Comment by aloiscochard** [comment]
Released with `0.4.0.4`, but this is not ideal, we could relatively easily support git based dependency I think, I created an issue relative to that:
https://github.com/aloiscochard/codex/issues/46
