### ISSUE TITLE
"ghc-pkg: Prelude.chr: bad argument: 3997250"

### ISSUE THREAD

**Issue by chreekat** [aloiscochard/codex#47]
Got this trying to run codex on [Snowdrift](https://git.gnu.io/snowdrift/snowdrift).

Note that I have ghc 7.8 installed globally, but Snowdrift uses 7.10.2 locally.

    Configuring Snowdrift-0.1.4...
    cabal: user error ('/home/b/.local/bin/ghc-pkg' exited with an error:
    ghc-pkg: Prelude.chr: bad argument: 3997250
    )
    codex: *warning* falling back on dependency resolution using hackage

**Comment by chreekat** [comment]
Not sure if related, but codex still continues and writes out a tags file -- which is depressingly sparse. Mostly it seems to include entries for 'main' of a bunch of test files included with packages; test files that aren't even exported by those packages.

**Comment by aloiscochard** [comment]
@chreekat did you got at least some warnings saying that packages could not be fetched?

If you can retry with `--force` just to confirm/infirm the warnings messages.

I'll try to do the fix for proper GHC support from stack, that would fix this one.

**Comment by chreekat** [comment]
@aloiscochard using --force has no effect on error messages, and there are none besides what I listed above.

I won't be surprised if this gets fixed when stack ghc is supported. :)

Thanks for working on this project! It seems really great.

**Comment by aloiscochard** [comment]
Fixed with https://github.com/aloiscochard/codex/commit/09a805a45222ec299a59ee65012229340e5239d7
