### ISSUE TITLE
case-sensitive tag search in vim

### ISSUE THREAD

**Issue by azadbolour** [aloiscochard/codex#51]
Hi,

I am using the generated codex tag file with vim (on a MAC) and it works fine. My default vim case settings are - :set ignorecase and :set smartcase.

When I try to go to a tag, vim seems to be doing a case-insensitive search of the codex tags file. To take an extreme case, I tried - :tag Eq - and got several matches for 'eq' as well as a match for 'EQ', but interestingly, none for 'Eq'.

If I change my case settings above to :set noignorecase and try - ':tag Eq' - again I get:

E432: Tags file not sorted codex.tags
E257: cstag: tag not found

Is there a way to set things up so the tag search for the codex-generated tags file is case-sensitive in vim?

Many thanks.

Azad

**Comment by aloiscochard** [comment]
@azadbolour Hi, you should remove the setting `set ignorecase` in your vim configuration.

Ref: http://stackoverflow.com/questions/7234072/case-insensitive-tag-searching-in-vim
