### ISSUE TITLE
stack- (and new cabal-)friendly feature: Look in subdirectories for cabal files

### ISSUE THREAD

**Issue by chreekat** [aloiscochard/codex#55]

**Comment by shajra** [comment]
Man, just ran into this today.  I know the real answer may be "pull requests welcome."  I'm definitely penalized right now for having multiple packages specified in a top-level stack.yaml.  Maybe I can put a stack.yaml in each subproject instead.  I'll have to play around and see what makes Intero in Emacs happy.

**Comment by bitemyapp** [comment]
I'm in the same situation here, can explain more detail if desired.

**Comment by capn-freako** [comment]
Me too.

I see the last comment posted on this issue is almost a year old.
Did someone find a work-around and forget to post a link, here?

Thanks!

**Comment by stites** [comment]
Running into this issue is my life now so I've added a bounty. @chreekat / @aloiscochard can you edit the issue description to include this bountysource badge?

    ![](https://api.bountysource.com/badge/issue?issue_id=33469373)

rendered:  ![](https://api.bountysource.com/badge/issue?issue_id=33469373)

**Comment by cydparser** [comment]
@stites does #76 fix this issue for you? Only the last commit is relevant to this issue.

**Comment by stites** [comment]
Yup -- thanks for taking this! I took a look at the code and got sidetracked trying to refactor codex to use the stack- and cabal- libraries directly. Kudos @cydparser for persevering. I've never closed out a bounty before, but I think it requires the PR to get merged into master and for this issue to be closed as a result.

**Comment by chreekat** [comment]
By all accounts, #76 resolves this issue. It's been merged, so I'm finally closing this. :)

/cc @stites
