### ISSUE TITLE
Adding codex to Stackage LTS >= 7

### ISSUE THREAD

**Issue by begriffs** [aloiscochard/codex#67]
Hi there, thanks for the codex tool. Love having it to help me make tags to jump into library code from my editor. A lot of other people are using it too through the haskell-vim-now project. Been getting a few issues (https://github.com/begriffs/haskell-vim-now/issues/233, https://github.com/begriffs/haskell-vim-now/issues/233) lately about install failures. Looks like this is because codex hasn't been in Stackage since LTS-6.30. Is there a way to get it back into Stackage?

**Comment by bitemyapp** [comment]
Need to nuke wreq out of it. Hasn't mattered for me too much because I `git clone` and `stack install` it, but I feel you.

https://github.com/fpco/stackage/pull/1890

**Comment by alx741** [comment]
+1 to this, would be glad to be able to `stack install codex`

**Comment by SX91** [comment]
Is there any reason to no just bump upper bounds for `wreq` and `directory`?

**Comment by aloiscochard** [comment]
The upper bounds are now fixed (https://github.com/aloiscochard/codex/issues/68), I hope that will solve building on stackage.

**Comment by alx741** [comment]
I confirm `stack install codex` now works perfectly

**Comment by aloiscochard** [comment]
Awesome, thanks for the feedback @alx741 !
