### ISSUE TITLE
codex update does not work in cabal sandbox

### ISSUE THREAD

**Issue by miladz68** [aloiscochard/codex#71]
in my mac OS X El Captian, when I run `codex update` in any sandbox, I get the following error : 

>┗❯ codex update
> codex: Saved package config file is outdated:
> • the Cabal version changed from Cabal-1.24.0.0 to Cabal-1.24.2.0
> • the compiler changed from ghc-7.10 to ghc-8.0
> Re-run the 'configure' command.
> codex: *warning* falling back on dependency resolution using hackage
> codex: Prelude.read: no parse

I updated my codex to version  0.5.1.2 from 0.5.02 but the problem persists.
when I type in terminal `cabal --version` I get ` cabal-install version 1.24.0.0` 
I used to have Cabal-1.24.2.0 but downgraded to version Cabal-1.24.0.0, I don't remember how I did this.

although codex update works outside the sandbox

**Comment by dan-t** [comment]
See https://github.com/aloiscochard/codex/pull/74.

**Comment by parsonsmatt** [comment]
Presuming fixed as of #74
