### ISSUE TITLE
`codex` fails if there's no cabal directory

### ISSUE THREAD

**Issue by parsonsmatt** [aloiscochard/codex#78]
```bash
$ codex
codex: NoHackageTarballFound
```

I am doing a fresh install on Ubuntu and haven't built any Haskell projects using `cabal` yet. Doing a `cabal update` fixes this issue.

The `hackage-db` package throws this exception if the file isn't found: https://github.com/peti/hackage-db/blob/master/src/Distribution/Hackage/DB/Path.hs#L43-L47

**Comment by roman** [comment]
Thanks for the tip

**Comment by parsonsmatt** [comment]
There are better error messages for this case now.
