### ISSUE TITLE
reported version is incorrect

### ISSUE THREAD

**Issue by JakeAndrew** [aloiscochard/codex#80]
*Note:* Fixing this bug may require something to be changed on Hackage, rather than in the repo.
Then again, maybe the repo does need an adjustment.

## How to recreate & prove the bug's existence:

First, navigate into a Stack project directory and run `stack install codex`.
This installs `codex` to `~/.local/bin`, at least with my config.

Now run `codex --version`. I got `codex: 0.5.1.2`.

`~/.local/bin/codex --version` gave the same for me.

Now, let's do a little binary forensics. Run `grep -a help ~/.local/bin/codex`.
This searches the binary file for the string "help", the `-a` flag telling grep
to treat the binary as text. This, of course, turns up at least one result
because the program has to recognize the `--help` command-line argument.

Now that we are convinced that we have the right grep command, run the same
command, but with `DISABLE` instead of `help`. In my case, this turned up *no*
results.

And yet it should have. Why? First, note that the program claims to be version
`0.5.1.2`. Now go to [Codex's homepage](https://github.com/aloiscochard/codex). Note the badge in the ReadMe says `v0.5.1.2`. 
Now navigate to [src/Codex/Project.hs](https://github.com/aloiscochard/codex/blob/master/src/Codex/Project.hs) and view line 90.

Ah ha. `DISABLE` should have turned up a grep result if we really did have
v0.5.1.2, according to the version on GitHub.

Now, when I download the current source from GitHub, compile it and run the
search for `DISABLE` on that binary, which also claims to be version 0.5.1.2,
I *do* get a hit.

So, we have two versions of the program, proven to be different from each other,
that both claim to be the same version. Therefore, something is reporting the
version incorrectly.

**Comment by parsonsmatt** [comment]
Any version of `codex` built with the `cabal` file specifying the version as `0.5.1.2` will do that. I suspect you installed a Git version of `codex` at some point that had that version tag.
